- name: Say Hello World
  host: all
  task:
    - name: Say Hello World
      ansible.builtin.debug:
       msg: Guten Morgan


- name: Say Hello World
  host: all
  task:
    - name: Say Hello World
      ansible.builtin.debug:
       msg: Guten Abend