- name: Demo on Variables
  hosts: localhost
  # if we declare variables here (play level)  then all tasks can access this variable
  vars:
    URL: play.google.com
  tasks:
    -name: Print Play level variable
     ansible.builtin.debug:
        msg: URL = {{ URL }}

  roles:
    - demo
    -




